/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WandsRouteImport } from './routes/wands'
import { Route as SpellsRouteImport } from './routes/spells'
import { Route as SortingHatRouteImport } from './routes/sorting-hat'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PotionsRouteImport } from './routes/potions'
import { Route as PatronusRouteImport } from './routes/patronus'
import { Route as MapRouteImport } from './routes/map'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as HousesRouteImport } from './routes/houses'
import { Route as HogwartsRouteImport } from './routes/hogwarts'
import { Route as DarkArtsRouteImport } from './routes/dark-arts'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CharactersRouteImport } from './routes/characters'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSortingHatRouteImport } from './routes/api/sorting-hat'
import { Route as ApiPatronusRouteImport } from './routes/api/patronus'
import { Route as ApiCharacterChatRouteImport } from './routes/api/character-chat'

const WandsRoute = WandsRouteImport.update({
  id: '/wands',
  path: '/wands',
  getParentRoute: () => rootRouteImport,
} as any)
const SpellsRoute = SpellsRouteImport.update({
  id: '/spells',
  path: '/spells',
  getParentRoute: () => rootRouteImport,
} as any)
const SortingHatRoute = SortingHatRouteImport.update({
  id: '/sorting-hat',
  path: '/sorting-hat',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PotionsRoute = PotionsRouteImport.update({
  id: '/potions',
  path: '/potions',
  getParentRoute: () => rootRouteImport,
} as any)
const PatronusRoute = PatronusRouteImport.update({
  id: '/patronus',
  path: '/patronus',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const HousesRoute = HousesRouteImport.update({
  id: '/houses',
  path: '/houses',
  getParentRoute: () => rootRouteImport,
} as any)
const HogwartsRoute = HogwartsRouteImport.update({
  id: '/hogwarts',
  path: '/hogwarts',
  getParentRoute: () => rootRouteImport,
} as any)
const DarkArtsRoute = DarkArtsRouteImport.update({
  id: '/dark-arts',
  path: '/dark-arts',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersRoute = CharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSortingHatRoute = ApiSortingHatRouteImport.update({
  id: '/api/sorting-hat',
  path: '/api/sorting-hat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPatronusRoute = ApiPatronusRouteImport.update({
  id: '/api/patronus',
  path: '/api/patronus',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCharacterChatRoute = ApiCharacterChatRouteImport.update({
  id: '/api/character-chat',
  path: '/api/character-chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/characters': typeof CharactersRoute
  '/chat': typeof ChatRoute
  '/daily': typeof DailyRoute
  '/dark-arts': typeof DarkArtsRoute
  '/hogwarts': typeof HogwartsRoute
  '/houses': typeof HousesRoute
  '/journal': typeof JournalRoute
  '/map': typeof MapRoute
  '/patronus': typeof PatronusRoute
  '/potions': typeof PotionsRoute
  '/profile': typeof ProfileRoute
  '/sorting-hat': typeof SortingHatRoute
  '/spells': typeof SpellsRoute
  '/wands': typeof WandsRoute
  '/api/character-chat': typeof ApiCharacterChatRoute
  '/api/patronus': typeof ApiPatronusRoute
  '/api/sorting-hat': typeof ApiSortingHatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/characters': typeof CharactersRoute
  '/chat': typeof ChatRoute
  '/daily': typeof DailyRoute
  '/dark-arts': typeof DarkArtsRoute
  '/hogwarts': typeof HogwartsRoute
  '/houses': typeof HousesRoute
  '/journal': typeof JournalRoute
  '/map': typeof MapRoute
  '/patronus': typeof PatronusRoute
  '/potions': typeof PotionsRoute
  '/profile': typeof ProfileRoute
  '/sorting-hat': typeof SortingHatRoute
  '/spells': typeof SpellsRoute
  '/wands': typeof WandsRoute
  '/api/character-chat': typeof ApiCharacterChatRoute
  '/api/patronus': typeof ApiPatronusRoute
  '/api/sorting-hat': typeof ApiSortingHatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/characters': typeof CharactersRoute
  '/chat': typeof ChatRoute
  '/daily': typeof DailyRoute
  '/dark-arts': typeof DarkArtsRoute
  '/hogwarts': typeof HogwartsRoute
  '/houses': typeof HousesRoute
  '/journal': typeof JournalRoute
  '/map': typeof MapRoute
  '/patronus': typeof PatronusRoute
  '/potions': typeof PotionsRoute
  '/profile': typeof ProfileRoute
  '/sorting-hat': typeof SortingHatRoute
  '/spells': typeof SpellsRoute
  '/wands': typeof WandsRoute
  '/api/character-chat': typeof ApiCharacterChatRoute
  '/api/patronus': typeof ApiPatronusRoute
  '/api/sorting-hat': typeof ApiSortingHatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/characters'
    | '/chat'
    | '/daily'
    | '/dark-arts'
    | '/hogwarts'
    | '/houses'
    | '/journal'
    | '/map'
    | '/patronus'
    | '/potions'
    | '/profile'
    | '/sorting-hat'
    | '/spells'
    | '/wands'
    | '/api/character-chat'
    | '/api/patronus'
    | '/api/sorting-hat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/characters'
    | '/chat'
    | '/daily'
    | '/dark-arts'
    | '/hogwarts'
    | '/houses'
    | '/journal'
    | '/map'
    | '/patronus'
    | '/potions'
    | '/profile'
    | '/sorting-hat'
    | '/spells'
    | '/wands'
    | '/api/character-chat'
    | '/api/patronus'
    | '/api/sorting-hat'
  id:
    | '__root__'
    | '/'
    | '/characters'
    | '/chat'
    | '/daily'
    | '/dark-arts'
    | '/hogwarts'
    | '/houses'
    | '/journal'
    | '/map'
    | '/patronus'
    | '/potions'
    | '/profile'
    | '/sorting-hat'
    | '/spells'
    | '/wands'
    | '/api/character-chat'
    | '/api/patronus'
    | '/api/sorting-hat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CharactersRoute: typeof CharactersRoute
  ChatRoute: typeof ChatRoute
  DailyRoute: typeof DailyRoute
  DarkArtsRoute: typeof DarkArtsRoute
  HogwartsRoute: typeof HogwartsRoute
  HousesRoute: typeof HousesRoute
  JournalRoute: typeof JournalRoute
  MapRoute: typeof MapRoute
  PatronusRoute: typeof PatronusRoute
  PotionsRoute: typeof PotionsRoute
  ProfileRoute: typeof ProfileRoute
  SortingHatRoute: typeof SortingHatRoute
  SpellsRoute: typeof SpellsRoute
  WandsRoute: typeof WandsRoute
  ApiCharacterChatRoute: typeof ApiCharacterChatRoute
  ApiPatronusRoute: typeof ApiPatronusRoute
  ApiSortingHatRoute: typeof ApiSortingHatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wands': {
      id: '/wands'
      path: '/wands'
      fullPath: '/wands'
      preLoaderRoute: typeof WandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spells': {
      id: '/spells'
      path: '/spells'
      fullPath: '/spells'
      preLoaderRoute: typeof SpellsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorting-hat': {
      id: '/sorting-hat'
      path: '/sorting-hat'
      fullPath: '/sorting-hat'
      preLoaderRoute: typeof SortingHatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/potions': {
      id: '/potions'
      path: '/potions'
      fullPath: '/potions'
      preLoaderRoute: typeof PotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patronus': {
      id: '/patronus'
      path: '/patronus'
      fullPath: '/patronus'
      preLoaderRoute: typeof PatronusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houses': {
      id: '/houses'
      path: '/houses'
      fullPath: '/houses'
      preLoaderRoute: typeof HousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hogwarts': {
      id: '/hogwarts'
      path: '/hogwarts'
      fullPath: '/hogwarts'
      preLoaderRoute: typeof HogwartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dark-arts': {
      id: '/dark-arts'
      path: '/dark-arts'
      fullPath: '/dark-arts'
      preLoaderRoute: typeof DarkArtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sorting-hat': {
      id: '/api/sorting-hat'
      path: '/api/sorting-hat'
      fullPath: '/api/sorting-hat'
      preLoaderRoute: typeof ApiSortingHatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/patronus': {
      id: '/api/patronus'
      path: '/api/patronus'
      fullPath: '/api/patronus'
      preLoaderRoute: typeof ApiPatronusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/character-chat': {
      id: '/api/character-chat'
      path: '/api/character-chat'
      fullPath: '/api/character-chat'
      preLoaderRoute: typeof ApiCharacterChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CharactersRoute: CharactersRoute,
  ChatRoute: ChatRoute,
  DailyRoute: DailyRoute,
  DarkArtsRoute: DarkArtsRoute,
  HogwartsRoute: HogwartsRoute,
  HousesRoute: HousesRoute,
  JournalRoute: JournalRoute,
  MapRoute: MapRoute,
  PatronusRoute: PatronusRoute,
  PotionsRoute: PotionsRoute,
  ProfileRoute: ProfileRoute,
  SortingHatRoute: SortingHatRoute,
  SpellsRoute: SpellsRoute,
  WandsRoute: WandsRoute,
  ApiCharacterChatRoute: ApiCharacterChatRoute,
  ApiPatronusRoute: ApiPatronusRoute,
  ApiSortingHatRoute: ApiSortingHatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
